version: '2'

services:

  database:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /mnt/DATA/airsonic-data/postgresql:/var/lib/postgresql/data
    ports:
      - 5433:5432

  airsonic:
    build:
      context: airsonic/
    volumes:
      - ${MUSIC_DIR}:/airsonic/music
      - /mnt/DATA/airsonic-data/airsonic/podcasts:/airsonic/podcasts
    devices:
      - /dev/snd
    ports:
      - "4040:4040"

networks:
  default:
    external:
      name: airsonic